apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-go-ebntzurw-workflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-go-ebntzurw-workflow 
  name: github-tests-go-ebntzurw-workflow
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: github-tests-go-ebntzurw-workflow
    weight: 100 
